FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt --verbose \
    && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')" \
    && rm -f requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "Class_WebApp_Streamlit.py"]
